require 'aws'
require 'active_model'
require 'active_dynamodb'
require 'support/mock_helpers'
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.mock_with :rspec
  config.filter_run_excluding :broken
  config.filter_run :focus
  config.run_all_when_everything_filtered = true
end
